version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - sh scripts/build.sh
      - echo Building the Docker image...
      - docker build -t sba-gov-katana .
      - docker tag sba-gov-katana:latest 536656293683.dkr.ecr.us-east-1.amazonaws.com/sba-gov-katana:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 536656293683.dkr.ecr.us-east-1.amazonaws.com/sba-gov-katana:latest