version: "3"
services:
  katana:
    build: .
    ports:
    - "3000:3000"
    environment:
    - NODE_ENV=docker
    volumes:
    - ./config:/usr/src/app/config
    depends_on:
    - mysql
    command: >
      /bin/bash -c "
        while ! nc -z mysql 3306;
        do
          echo waiting for mysql;
          sleep 1;
        done;
        echo Connected to mysql!;
        node app.js
      "
  mysql:
    image: "mysql:5.6"
    volumes:
    - ./scripts/db/katana_sql:/docker-entrypoint-initdb.d
    - /var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password123

