foresee:
    environment: staging
server:
    fqdn: amy.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeAmy
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectAmy
    borrowerChatbot:
        baseUrl: 'borrowerbot-web-ui-codebuilddeploy-1-webappbucket-1fy48fwc62ekq.s3.us-west-2.amazonaws.com'
miscapi:
  endpoint: mnk7e0ukgg.execute-api.us-east-1.amazonaws.com/latest/
sizestandards:
    endpoint: 27b9p5e3fk.execute-api.us-east-1.amazonaws.com/LATEST/
content:
    cloudfront: d1utnfrh2o11a6.cloudfront.net
    useD8EventsBackend: true
