foresee:
    environment: staging
server:
    fqdn: amy.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeAmy
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectAmy
sizestandards:
    endpoint: 27b9p5e3fk.execute-api.us-east-1.amazonaws.com/LATEST/
