developmentOptions:
    client:
        logging: true
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
foresee:
    environment: staging
miscapi:
  endpoint: 9hculkgtb7.execute-api.us-east-1.amazonaws.com/latest/
server:
    fqdn: avery.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeAvery
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectAvery
content:
    cloudfront: d15dl68v0dt33i.cloudfront.net
