foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: avery.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeAvery
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectAvery
cache:
  s3BucketName: avery-content-sba-gov
  useS3: true
offices:
    aws:
        cloudsearch:
            endpoint: 'doc-sba-gov-avery-office-qaz2dhbhpgzyolgczy4uf2cn7q.us-east-1.cloudsearch.amazonaws.com'
