developmentOptions:
    client:
        logging: true
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
foresee:
    environment: staging
miscapi:
    endpoint: mpmhqtea8g.execute-api.us-east-1.amazonaws.com/latest/ # mint
    # endpoint: 9hculkgtb7.execute-api.us-east-1.amazonaws.com/latest/ # avery
loanprocessing:
    endpoint: mint.ussba.io/api/loan-processing
server:
    fqdn: mint.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeIntegration
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectIntegration
content:
    endpoint: 61ebndrk8a.execute-api.us-east-1.amazonaws.com/latest # mint
    cloudfront: d32xeasjw66w65.cloudfront.net # mint
    #cloudfront: d8ptg6c733nbj.cloudfront.net # avery
    useD8EventsBackend: false