foresee:
    environment: staging
server:
    fqdn: avery.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeAvery
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectAvery
cache:
  s3BucketName: avery-content-sba-gov
  useS3: true
