foresee:
    environment: staging
miscapi:
  endpoint: 8hdsm8tbwd.execute-api.us-east-1.amazonaws.com/latest/
loanprocessing:
    endpoint: brian.ussba.io/api/loan-processing
server:
    fqdn: brian.ussba.io
features:
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectBrian
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeBrian
        enabled: true
content:
    cloudfront: d24l989bmg52r3.cloudfront.net
    useD8EventsBackend: true
