foresee:
    environment: staging
server:
    fqdn: brian.ussba.io
features:
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectBrian
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeBrian
        enabled: true
