foresee:
    environment: staging
server:
    fqdn: brian.ussba.io
features:
    forPartners: true
    showSbic: false
    moon: true
    urlRedirect:
        tableName: UrlToNodeBrian
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectBrian
cache:
  s3BucketName: brian-content-sba-gov
  useS3: true
