foresee:
    environment: staging
server:
    fqdn: brian.ussba.io
features:
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectBrian
    forPartners: true
    moon: true
    pressRelease: false
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeBrian
        enabled: true
cache:
  s3BucketName: brian-content-sba-gov
  useS3: true
