foresee:
    environment: staging
miscapi:
  endpoint: 8hdsm8tbwd.execute-api.us-east-1.amazonaws.com/latest/
server:
    fqdn: brian.ussba.io
features:
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectBrian
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeBrian
        enabled: true
content:
    cloudfront: dj898ero1amg0.cloudfront.net
    useD8EventsBackend: true
