foresee:
    environment: staging
server:
    fqdn: brian.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeBrian
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectBrian
cache:
  s3BucketName: brian-content-sba-gov
  useS3: true
