server:
  port: PORT
daisho:
  hostname: DAISHO_HOSTNAME
  port: DAISHO_PORT
database:
  nonDrupal:
    databaseName: DATABASE_NAME
    host: DATABASE_HOST
    password: DATABASE_PASSWORD
    user: DATABASE_USER
aws:
  accessKey: ACCESS_KEY_ID
  secretKey: SECRET_ACCESS_KEY
