server:
  port: PORT
  fqdn: FQDN
database:
  nonDrupal:
    databaseName: DATABASE_NAME
    host: DATABASE_HOST
    password: DATABASE_PASSWORD
    user: DATABASE_USER
  drupal:
    databaseName: DATABASE_NAME_DRUPAL7
    host: DATABASE_HOST_DRUPAL7
    password: DATABASE_PASSWORD_DRUPAL7
    user: DATABASE_USER_DRUPAL7
email:
  password: SMTP_PASSWORD
  username: SMTP_USERNAME
sizestandards:
  endpoint: SIZE_STANDARDS_ENDPOINT
googleMapsApiKey: GOOGLE_MAPS_API_KEY
content:
  endpoint: CONTENT_URL
misc:
  endpoint: MISC_API_URL