server:
  port: PORT
  fqdn: FQDN
database:
  nonDrupal:
    databaseName: DATABASE_NAME
    host: DATABASE_HOST
    password: DATABASE_PASSWORD
    user: DATABASE_USER
  drupal:
    databaseName: DATABASE_NAME_DRUPAL7
    host: DATABASE_HOST_DRUPAL7
    password: DATABASE_PASSWORD_DRUPAL7
    user: DATABASE_USER_DRUPAL7
email:
  password: SMTP_PASSWORD
  username: SMTP_USERNAME
oca:
  soap:
    username: OCA_SOAP_USER
    passwordDecryptionKey: OCA_SOAP_DECRYPTION_KEY
sizestandards:
    endpoint: SIZE_STANDARDS_ENDPOINT
cache:
  s3BucketName: S3BUCKET
publicPath: PUBLIC_PATH
googleMapsApiKey: GOOGLE_MAPS_API_KEY
