developmentOptions:
    webpack:
        enabled: false
        silent: false
drupal:
    hostname: http://wakizashi/
    enablePassThrough: false
server:
    port: 3000
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <lendermatch@sba.gov>'
    hostname: placeholder
    username: placeholder
    password: placeholder
linc:
    confirmationEmailBase: http://sbagov.fearlesstesters.com
database:
    mongoConnectString: mongodb://mongodb:27017/sba
    mysql:
      connectionLimit: 100
      database: placeholder
      host: placeholder
      password: placeholder
      user: placeholder
