developmentOptions:
    webpack:
        enabled: false
        silent: false
newrelic:
    enabled: false
drupal:
    hostname: http://localhost/
    enablePassThrough: false
    endpoint: rest
server:
    port: 3000
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <lendermatch@sba.gov>'
    hostname: placeholder
    username: placeholder
    password: placeholder
linc:
    confirmationEmailBase: http://sbagov.fearlesstesters.com
    resendEmailCron: '0 0 * * * *'
    lookback: 86400
    numberOfSecondsForWhichEmailIsValid: 172800
database:
    pool:
        max: 100
        min: 0
        idle: 1000
    nonDrupal:
        databaseName: placeholder
        host: placeholder
        password: placeholder
        user: placeholder
    drupal:
        databaseName: placeholder
        host: placeholder
        password: placeholder
        user: placeholder
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.cfc
