server:
    port: 3000
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <answerdesk@sba.gov>'
    hostname: overrideInHostnameYaml
    username: overrideInHostnameYaml
    password: overrideInHostnameYaml
linc:
    confirmationEmailBase: "http://ec2-52-23-225-150.compute-1.amazonaws.com"
database:
    mongoConnectString: mongodb://mongodb:27017/sba
