developmentOptions:
    webpack:
        enabled: false
        silent: false
    drupal:
        proxy: false
        hostname: http://sbagov-drupal.fearlesstesters.com/
server:
    port: 3000
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <lendermatch@sba.gov>'
    hostname: placeholder
    username: placeholder
    password: placeholder
linc:
    confirmationEmailBase: http://sbagov.fearlesstesters.com
database:
    mongoConnectString: mongodb://mongodb:27017/sba