developmentOptions:
    devMode: false
    client:
        logging: false
    redux:
        logging: false
    webpack:
        enabled: false
        silent: false
govdelivery:
    popupEnabled: false
foresee:
    environment: staging
    enabled: false
googleAnalytics:
    enabled: false
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
server:
    port: 3000
counsellorCta:
    nodeId: 6
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <lendermatch@sba.gov>'
    hostname: email-smtp.us-east-1.amazonaws.com
    password: placeholder
    username: placeholder
linc:
    resendEmailJobEnabled: false
    resendEmailCron: '0 0 * * * *'
    sendToOcaJobEnabled: false
    ocaSoapCron: '0 * * * * *'
    sendToLincPasswordUpdateEnabled: false
    ocaPasswordUpdateCron: '0 0 0 * * *'
    ocaVersion: 2
    lookback: 86400
    numberOfSecondsForWhichEmailIsValid: 172800
database:
    pool:
        max: 100
        min: 0
        idle: 1000
    nonDrupal:
        databaseName: placeholder
        host: placeholder
        password: placeholder
        user: placeholder
    drupal:
        databaseName: sba
        host: placeholder
        password: placeholder
        user: placeholder
oca:
    soap:
        username: placeholder
        passwordDecryptionKey: placeholderDecryptionKeyMustBeAtLeast16Characters
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.wsdl
features:
    showSbic: false
    geoLocator: false
    searchUrl: "/search/?q="
    urlRedirect:
        tableName: placeholder
        enabled: false
    drupalRedirect:
        enabled: false
        tableName: DrupalUrlRedirect
    true404: false
    office:
        sbaOfficeNames: ['SBA district office', 'SBA regional office']
    pressRelease: true
sizestandards:
    endpoint: placeholder
cache:
  s3BucketName: dev1-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    searchEndpoint: 'doc-mint-hdgvyg66mwvfnu46tzaszesh5u.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-mint-offices-mjhazqnua7k5nqkxojddfhkrw4.us-east-1.cloudsearch.amazonaws.com'
    zipCodeDynamoDBTableName: ZipCodesLower
  dynamodb:
    endpoint: placeholder
publicPath: "/build/"
nginx:
  katanaRedirectPaths: 'api|assets|build|lendermatch|actions|styleguide|business-guide|funding-programs|document|article|disaster-assistance|partners|naics|isSmallBusiness|size-standards|resource-partner-survey|learning-center|course|federal-contracting|search|national-small-business-week|nsbw'
googleMapsApiKey: placeholder
