developmentOptions:
    webpack:
        enabled: false
        silent: false
drupal:
    hostname: http://localhost/
    enablePassThrough: false
    endpoint: rest
server:
    port: 3000
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <lendermatch@sba.gov>'
    hostname: placeholder
    username: placeholder
    password: placeholder
linc:
    confirmationEmailBase: http://sbagov.fearlesstesters.com
    resendEmailCron: '0 0 0 * * *'
    resendFrequency: 86400
    numberOfSecondsForWhichEmailIsValid: 86400
database:
    mongoConnectString: mongodb://mongodb:27017/sba
    mysql:
      connectionLimit: 100
      database: placeholder
      host: placeholder
      password: placeholder
      user: placeholder
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.cfc
