developmentOptions:
    client:
        logging: false
    redux:
        logging: false
    webpack:
        enabled: false
        silent: false
    useLocalDataNotDaisho: false
govdelivery:
    popupEnabled: true
foresee:
    environment: staging
    enabled: true
newrelic:
    enabled: false
googleAnalytics:
    enabled: true
    accountId: "UA-19362636-5"
    optimizeContainerId: "GTM-NPDXPPF"
    tagManagerAccountId: "GTM-MSNZZ6M"
    debug: false
server:
    port: 3000
counsellorCta:
    nodeId: 6
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <lendermatch@sba.gov>'
    hostname: email-smtp.us-east-1.amazonaws.com
    password: placeholder
    username: placeholder
linc:
    confirmationEmailBase: http://sbagov.fearlesstesters.com
    resendEmailJobEnabled: false
    resendEmailCron: '0 0 * * * *'
    sendToOcaJobEnabled: true
    ocaSoapCron: '0 * * * * *'
    sendToLincPasswordUpdateEnabled: true
    ocaPasswordUpdateCron: '0 0 0 * * *'
    ocaVersion: 2
    lookback: 86400
    numberOfSecondsForWhichEmailIsValid: 172800
daisho:
    hostname: http://daisho
    port: 3000
database:
    pool:
        max: 100
        min: 0
        idle: 1000
    nonDrupal:
        databaseName: placeholder
        host: placeholder
        password: placeholder
        user: placeholder
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb.sba.gov/lendermatch/ws/linc.wsdl
