developmentOptions:
    devMode: false
    client:
        logging: false
    redux:
        logging: false
    webpack:
        enabled: false
        silent: false
    assets:
      endpoint: placeholder
govdelivery:
    popupEnabled: false
foresee:
    environment: staging
    enabled: false
googleAnalytics:
    enabled: false
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
server:
    port: 3000
    fqdn: placeholder
counselorCta:
    nodeId: 6
features:
    localAssistMenuHeight: true
    showSbic: false
    geoLocator: false
    searchUrl: "/search/?q="
    urlRedirect:
        tableName: placeholder
        enabled: false
    drupalRedirect:
        enabled: false
        tableName: DrupalUrlRedirect
    true404: true
    office:
        sbaOfficeNames: ['SBA district office', 'SBA regional office']
    pressRelease: true
sizestandards:
    endpoint: placeholder
aws:
  cloudsearch:
    searchEndpoint: 'doc-mint-hdgvyg66mwvfnu46tzaszesh5u.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-mint-offices-mjhazqnua7k5nqkxojddfhkrw4.us-east-1.cloudsearch.amazonaws.com'
    zipCodeDynamoDBTableName: ZipCodesLower
  dynamodb:
    endpoint: placeholder
googleMapsApiKey: placeholder
content:
  endpoint: placeholder
miscapi:
  endpoint: placeholder
meta:
  title: 'Small Business Administration'
  description: "We support America's small businesses. The SBA connects entrepreneurs with lenders and funding to help them plan, start and grow their business."
