developmentOptions:
    client:
        logging: false
    redux:
        logging: false
    webpack:
        enabled: false
        silent: false
newrelic:
    enabled: false
googleAnalytics:
    enabled: true
    accountId: "UA-19362636-5"
    debug: false
drupal:
    hostname: http://www.sba.gov/
    endpoint: rest
drupal8:
    hostname: tanto
server:
    port: 3000
email:
    debugEmailOnly: false
    sender: '"Small Business Administration" <jking@fearless.tech>'
    hostname: email-smtp.us-east-1.amazonaws.com
    password: placeholder
    username: placeholder
linc:
    confirmationEmailBase: http://sbagov.fearlesstesters.com
    resendEmailJobEnabled: true
    resendEmailCron: '0 0 * * * *'
    sendToOcaJobEnabled: true
    ocaSoapCron: '0 * * * * *'
    lookback: 86400
    numberOfSecondsForWhichEmailIsValid: 172800
database:
    pool:
        max: 100
        min: 0
        idle: 1000
    nonDrupal:
        databaseName: placeholder
        host: placeholder
        password: placeholder
        user: placeholder
    drupal:
        databaseName: placeholder
        host: placeholder
        password: placeholder
        user: placeholder
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.cfc
