foresee:
    environment: staging
server:
    fqdn: dev1.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeDev1
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectDev1
cache:
  s3BucketName: dev1-content-sba-gov
  useS3: true
