developmentOptions:
    webpack:
        enabled: true
        silent: false
drupal:
    hostname: http://sbagov-drupal.fearlesstesters.com/
email:
    debugEmailOnly: false
database:
    mongoConnectString: mongodb://localhost:27017/sba
linc:
    confirmationEmailBase: http://localhost:3000
