server:
  fqdn: localhost
developmentOptions:
    client:
        logging: true
    redux:
        logging: true
    webpack:
        enabled: true
        silent: false
govdelivery:
    popupEnabled: false
foresee:
    enabled: false
aws:
  dynamodb:
    endpoint: UrlToNodeDev1
features:
  urlRedirect:
    tableName: UrlToNodeDev1
    enabled: true
  drupalRedirect:
    tableName: UrlToUrlRedirectDev1
