developmentOptions:
    webpack:
        enabled: true
        silent: false
drupal:
    hostname: https://www.sbagov2.fearlesstesters.com/
email:
    debugEmailOnly: false
database:
    nonDrupal:
        databaseName: sba_katana
        host: localhost
        password: placeholder
        user: placeholder
    drupal:
        databaseName: sba_drupal
        host: localhost
        password: placeholder
        user: placeholder
linc:
    confirmationEmailBase: http://localhost:3000
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.cfc
