developmentOptions:
    redux:
        logging: true
    webpack:
        enabled: true
        silent: false
govdelivery:
    popupEnabled: false
googleAnalytics:
    accountId: "UA-96147768-2"
    tagManagerAccountId: "GTM-KVLNXBH"
    optimizeContainerId: "GTM-KS9GT4X"
    debug: true
drupal:
    hostname: https://www.sbagov.fearlesstesters.com/
drupal8:
    hostname: http://content.sbagov.fearlesstesters.com/
    useLocalContacts: true
database:
    nonDrupal:
        databaseName: sba_katana
        host: localhost
        password: password123
        user: root
    drupal:
        databaseName: sba_drupal
        host: localhost
        password: password123
        user: root
linc:
    confirmationEmailBase: http://localhost:3000
    resendEmailJobEnabled: false
    sendToOcaJobEnabled: false
    sendToLincPasswordUpdateEnabled: false
oca:
    soap:
        wsdlUrl: https://catweb2.sba.gov/lendermatch/ws/linc.wsdl
