developmentOptions:
    devMode: false
    client:
        logging: true
    redux:
        logging: true
    webpack:
        enabled: true
        silent: false
govdelivery:
    popupEnabled: false
foresee:
    enabled: false
googleAnalytics:
    accountId: "UA-96147768-2"
    tagManagerAccountId: "GTM-KVLNXBH"
    optimizeContainerId: "GTM-KS9GT4X"
    debug: true
database:
    nonDrupal:
        databaseName: sba_katana
        host: localhost
        password: password123
        user: root
    drupalSeven:
        databaseName: sba_prod
        host: localhost
        password: password123
        user: root
linc:
    confirmationEmailBase: http://localhost:3000
    resendEmailJobEnabled: false
    sendToOcaJobEnabled: false
    sendToLincPasswordUpdateEnabled: false
oca:
    soap:
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.wsdl
features:
    forPartners: true
cache:
  s3BucketName: dev-content-sba-gov
