developmentOptions:
    webpack:
        enabled: true
        silent: false
drupal:
    hostname: http://sbagov.fearlesstesters.com/
email:
    debugEmailOnly: false
database:
    mongoConnectString: mongodb://localhost:27017/sba
linc:
    confirmationEmailBase: http://localhost:3000
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.cfc
