developmentOptions:
    webpack:
        enabled: true
        silent: false
    drupal:
        proxy: false
        hostname: http://sbagov-drupal.fearlesstesters.com/
email:
    debugEmailOnly: false
database:
    mongoConnectString: mongodb://localhost:27017/sba
linc:
    confirmationEmailBase: http://localhost:3000
