server:
  fqdn: localhost
developmentOptions:
    client:
        logging: true
    redux:
        logging: true
    webpack:
        enabled: true
        silent: false
govdelivery:
    popupEnabled: false
foresee:
    enabled: false
database:
    nonDrupal:
        databaseName: sba_katana
        host: localhost
        password: password123
        user: root
    drupal:
        databaseName: sba_prod
        host: localhost
        password: password123
        user: root
aws:
  dynamodb:
    endpoint: UrlToNodeDev1
features:
  urlRedirect:
    tableName: UrlToNodeDev1
    enabled: true
  drupalRedirect:
    tableName: UrlToUrlRedirectDev1
