developmentOptions:
    redux:
        logging: true
    webpack:
        enabled: true
        silent: false
googleAnalytics:
    accountId: "UA-96147768-1"
    debug: true
drupal:
    hostname: https://www.sbagov.fearlesstesters.com/
database:
    nonDrupal:
        databaseName: sba_katana
        host: localhost
        password: testuser
        user: Password123
    drupal:
        databaseName: sba_drupal
        host: localhost
        password: testuser
        user: Password123
linc:
    confirmationEmailBase: http://localhost:3000
oca:
    soap:
        username: placeholder
        password: placeholder
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.cfc
