foresee:
    environment: staging
server:
    fqdn: devf.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/search/?q="
    urlRedirect:
        tableName: UrlToNodeDevF
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectDevF
cache:
  s3BucketName: devf-content-sba-gov
  useS3: true
