foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: devf.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/search/?q="
    urlRedirect:
        tableName: UrlToNodeDevF
        enabled: false
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectDevF
cache:
  s3BucketName: devf-content-sba-gov
  useS3: true
