
drupal:
    seven:
        hostname: http://devf.sba.fun/
        databaseName: sba_prod
    eight:
        hostname: http://devf-content.sba.fun/
        cloudSearch:
            enabled: true
database:
    host: db.devf.sba.fun

temp:
    enableFundingProgramsMenu: true
