database:
    nonDrupal:
        databaseName: sba_katana
        host: mysql
        password: password123
        user: root
googleAnalytics:
    enabled: false
foresee:
    enabled: false
linc:
    confirmationEmailBase: http://localhost:3000
    resendEmailJobEnabled: false
    sendToOcaJobEnabled: false
    sendToLincPasswordUpdateEnabled: false
oca:
    soap:
        wsdlUrl: https://catweb2.sba.gov/linc/ws/linc.wsdl
daisho:
    hostname: http://34.232.40.131
    port: 80
