foresee:
    environment: staging
miscapi:
  endpoint: 5l7gyiyjzh.execute-api.us-east-1.amazonaws.com/latest/
loanprocessing:
    endpoint: kevin.ussba.io/api/loan-processing
server:
    fqdn: kevin.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeKevin
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectKevin
content:
    cloudfront: d3f48ijg0l2tm.cloudfront.net
    useD8EventsBackend: true
