foresee:
    environment: staging
server:
    fqdn: kevin.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    urlRedirect:
        tableName: UrlToNodeKevin
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectKevin
cache:
    s3BucketName: kevin-content-sba-gov
    useS3: true
