foresee:
    environment: staging
server:
    fqdn: kevin.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeKevin
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectKevin
