foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: kevin.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: /search/?q=
    urlRedirect:
        tableName: UrlToNodeKevin
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectKevin
cache:
    s3BucketName: kevin-content-sba-gov
    useS3: true
