foresee:
    environment: staging
server:
    fqdn: laura.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false

    searchUrl: /search/?q=
    urlRedirect:
        tableName: UrlToNodeLaura
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectLaura
cache:
  s3BucketName: laura-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    searchEndpoint: 'doc-laura-26evoc5xorgki5mbhdiktpp7q4.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-laura-offices-ovmfppym46ea6hgq6ms2f6d3ye.us-east-1.cloudsearch.amazonaws.com'
database:
    pool:
        max: 100
        min: 0
        idle: 1000
    nonDrupal:
        databaseName: sba_katana
        host: legacy-data.cdhrzroeeqks.us-east-1.rds.amazonaws.com
        password: Fearless1
        user: sbagov
