foresee:
    environment: staging
server:
    fqdn: laura.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeLaura
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectLaura
cache:
  s3BucketName: laura-content-sba-gov
  useS3: true
sizestandards:
    endpoint: ruay9oz348.execute-api.us-east-1.amazonaws.com/LATEST/