foresee:
    environment: staging
server:
    fqdn: laura.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeLaura
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectLaura
sizestandards:
    endpoint: 27b9p5e3fk.execute-api.us-east-1.amazonaws.com/LATEST/
