foresee:
    environment: staging
server:
    fqdn: laura.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeLaura
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectLaura
cache:
  s3BucketName: laura-content-sba-gov
  useS3: true
