googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
foresee:
    environment: staging
server:
    fqdn: mint.ussba.io
features:
    localAssistMenuHeight: true
    geoLocator: false
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeIntegration
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectIntegration
