foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: mint.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeStaging
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectStaging
cache:
  s3BucketName: mint-content-sba-gov
  useS3: true
