googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
foresee:
    environment: staging
server:
    fqdn: mint.ussba.io
features:
    geoLocator: false
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeIntegration
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectIntegration
    true404: true
cache:
  s3BucketName: mint-content-sba-gov
  useS3: true
