foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: mint.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: '/search/?q='
    urlRedirect:
        tableName: UrlToNodeIntegration
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectIntegration
    true404: true
cache:
  s3BucketName: mint-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    search-endpoint: 'doc-integration-l3hya3o2kdvr3gpbxb33qznllm.us-east-1.cloudsearch.amazonaws.com'
