foresee:
    environment: staging
miscapi:
  endpoint: lv3rqu1y3g.execute-api.us-east-1.amazonaws.com/latest/
server:
    fqdn: pat.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodePat
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectPat
sizestandards:
    endpoint: 27b9p5e3fk.execute-api.us-east-1.amazonaws.com/LATEST/
content:
    cloudfront: d1a2l9h01zaqn1.cloudfront.net
    #cloudfront: d2oe9i2bio9fwb.cloudfront.net
    useD8EventsBackend: true
