foresee:
    environment: production
googleAnalytics:
    enabled: false
    accountId: UA-19362636-5
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-MSNZZ6M
server:
    fqdn: sba.gov
features:
    localAssistMenuHeight: false
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeProduction
        enabled: true
    drupalRedirect:
        tableName: UrlToUrlRedirectProduction
        enabled: true
aws:
  cloudsearch:
    searchEndpoint: 'doc-production-b4waq4e3rl6daphct5rtlxjmmm.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-production-offices-lzpi5yk5h5c6jaa42nqkrtxm6e.us-east-1.cloudsearch.amazonaws.com'
    zipCodeDynamoDBTableName: ZipCodesUpper
content:
    cloudfront: d1iy86qyaex0mm.cloudfront.net