foresee:
    environment: production
googleAnalytics:
    enabled: false
    accountId: UA-19362636-5
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-MSNZZ6M
server:
    fqdn: sba.gov
features:
    forPartners: true
    showSbic: false
    moon: true
    urlRedirect:
        tableName: UrlToNodeProduction
        enabled: true
    drupalRedirect:
        tableName: UrlToUrlRedirectProduction
        enabled: true
linc:
  resendEmailJobEnabled: false
  sendToOcaJobEnabled: false
  sendToLincPasswordUpdateEnabled: false
oca:
    soap:
        wsdlUrl: https://caweb.sba.gov/linc/ws/linc.wsdl
cache:
  s3BucketName: production-aws-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    searchEndpoint: 'doc-production-b4waq4e3rl6daphct5rtlxjmmm.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-production-offices-lzpi5yk5h5c6jaa42nqkrtxm6e.us-east-1.cloudsearch.amazonaws.com'
