foresee:
    environment: production
googleAnalytics:
    enabled: false
    accountId: UA-19362636-5
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-MSNZZ6M
miscapi:
  content: w1yv86ffx7.execute-api.us-east-1.amazonaws.com/latest/
loanprocessing:
    endpoint: sba.gov/api/loan-processing
server:
    fqdn: www.sba.gov
features:
    localAssistMenuHeight: false
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeProduction
        enabled: true
    drupalRedirect:
        tableName: UrlToUrlRedirectProduction
        enabled: true
    breakEvenCalculator:
        enabled: false
aws:
  cloudsearch:
    searchEndpoint: 'doc-production-b4waq4e3rl6daphct5rtlxjmmm.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-production-offices-lzpi5yk5h5c6jaa42nqkrtxm6e.us-east-1.cloudsearch.amazonaws.com'
    zipCodeDynamoDBTableName: ZipCodesUpper
content:
    cloudfront: d1iy86qyaex0mm.cloudfront.net
    useD8EventsBackend: false
