foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: qaint.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeIntegration
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectIntegration
cache:
  s3BucketName: qint-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    endpoint: 'doc-qaint-6x5ozxz66ceh74wz3bdbacbl2e.us-east-1.cloudsearch.amazonaws.com'
