googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
foresee:
    environment: staging
server:
    fqdn: ryan.ussba.io
features:
    forPartners: true
    showSbic: false
    moon: false
    urlRedirect:
        tableName: UrlToNodeRyan
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectRyan
cache:
  s3BucketName: ryan-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    officeEndpoint: 'doc-ryan-viytyt5s4g2yoosw7skocf2v64.us-east-1.cloudsearch.amazonaws.com'
