googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
foresee:
    environment: staging
miscapi:
  endpoint: hcn9xuw0qc.execute-api.us-east-1.amazonaws.com/latest/
loanprocessing:
    endpoint: ryan.ussba.io/api/loan-processing
server:
    fqdn: ryan.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeRyan
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectRyan
content:
    cloudfront: d2gpg521ydb1gz.cloudfront.net
    useD8EventsBackend: true


