foresee:
    environment: staging
server:
    fqdn: staging.sba.fun
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeStaging
    drupalRedirect:
        tableName: UrlToUrlRedirectStaging
cache:
  s3BucketName: staging-aws-content-sba-gov
  useS3: true
