foresee:
    environment: staging
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
server:
    fqdn: staging-www.sba.gov
features:
    forPartners: true
    showSbic: false
    moon: false
    searchUrl: "/tools/search-result-page?search="
    urlRedirect:
        tableName: UrlToNodeStaging
        enabled: false
    drupalRedirect:
        tableName: UrlToUrlRedirectStaging
        enabled: false
    true404: false
cache:
  s3BucketName: staging-content-sba-gov
  useS3: true
