foresee:
    environment: staging
server:
    fqdn: staging.sba.gov
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeStaging
        enabled: true
    drupalRedirect:
        tableName: UrlToUrlRedirectStaging
        enabled: true
cache:
  s3BucketName: staging-aws-content-sba-gov
  useS3: true
aws:
  cloudsearch:
    searchEndpoint: 'doc-staging-2qt6cxrxhpdkdv5pnjgw54wzqi.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-staging-offices-igktog6nphm6kuwkkkj52j2rba.us-east-1.cloudsearch.amazonaws.com'
    zipCodeDynamoDBTableName: ZipCodesUpper
