foresee:
    environment: staging
miscapi:
  endpoint: ii16pmq7e6.execute-api.us-east-1.amazonaws.com/latest/
server:
    fqdn: staging.sba.gov
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeStaging
        enabled: true
    drupalRedirect:
        tableName: UrlToUrlRedirectStaging
        enabled: true
aws:
  cloudsearch:
    searchEndpoint: 'doc-staging-2qt6cxrxhpdkdv5pnjgw54wzqi.us-east-1.cloudsearch.amazonaws.com'
    officeEndpoint: 'doc-staging-offices-igktog6nphm6kuwkkkj52j2rba.us-east-1.cloudsearch.amazonaws.com'
    zipCodeDynamoDBTableName: ZipCodesUpper
content:
    cloudfront: d1ibwq49g7xqd4.cloudfront.net
    useD8EventsBackend: false
