developmentOptions:
    client:
        logging: true
googleAnalytics:
    enabled: true
    accountId: UA-96147768-1
    optimizeContainerId: GTM-NPDXPPF
    tagManagerAccountId: GTM-WN49BK2
    debug: false
server:
    fqdn: venus.ussba.io
features:
    showSbic: false
    urlRedirect:
        tableName: UrlToNodeVenus
        enabled: true
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectVenus
content:
    cloudfront: d296wys6s7bkek.cloudfront.net
    useD8EventsBackend: false