version: "2"
services:
  mysql:
    image: mysql:5.6
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: "sba_drupal8"
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
        - "3306:3306"
    restart: always
    volumes:
      - ${MYSQL_DIRECTORY}:/var/lib/mysql
  drupal:
    image: drupal:8
    ports:
      - "8080:80"
    links:
      - mysql
